version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  auth:
    image: auth:v0.0.1
    container_name: auth_server
    ports:
      - "8000:8000"
    volumes:
      - auth_data:/app/data
    command: ["java", "-Duser.timezone=Asia/Seoul", "-jar", "/app/auth.jar"]

volumes:
  redis_data:
  auth_data: