server:
  port: 8001

spring:
  application:
    name: auth

  config:
    import:
      - classpath:app/security/cors.yml
      - classpath:app/security/jwt.yml
      - classpath:app/security/auth.yml

  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379
    password: redis1004